# Generated by Django 5.0.3 on 2024-04-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_alter_customusers_kebele_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
