# Generated by Django 5.0.3 on 2024-09-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_customusers_is_orginization_customusers_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
