# Generated by Django 5.0.3 on 2024-04-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0003_alter_customusers_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='customusers',
            name='user_status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending')], default='active', max_length=20),
        ),
    ]
