# Generated by Django 5.0.3 on 2024-04-24 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0004_customusers_profile_photo_customusers_user_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customusers',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='customusers',
            name='last_name',
        ),
    ]
