# Generated by Django 5.0.3 on 2024-06-04 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LookUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.FloatField(default=1.0)),
                ('CO2_reducedValue', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='WastePlastic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wastePlastic_type', models.CharField(max_length=100)),
                ('collection_date', models.DateField(auto_now_add=True)),
                ('wastePlastic_size', models.PositiveIntegerField()),
                ('pickUp_status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='pending', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WastePlasticRequestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wastePlastic_type', models.CharField(max_length=100)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('request_time', models.TimeField(auto_now_add=True)),
                ('wastePlastic_size', models.PositiveIntegerField()),
                ('wastePlastic_address', models.CharField(blank=True, max_length=100, null=True)),
                ('unique_location', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, max_length=50, null=True)),
                ('longitude', models.FloatField(blank=True, max_length=50, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('pickUp_status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='pending', max_length=100)),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asign_status', models.CharField(choices=[('asign', 'Asign'), ('take back', 'Take back')], default='asign', max_length=100)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('requestId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WastePlasticCollectorApp.wasteplasticrequestor')),
            ],
        ),
        migrations.CreateModel(
            name='RequestPickUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_status', models.CharField(choices=[('accept', 'Accept'), ('reject', 'Reject'), ('pending', 'Pending')], default='pending', max_length=100)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('requestId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WastePlasticCollectorApp.wasteplasticrequestor')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('wastePlasticRequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WastePlasticCollectorApp.wasteplasticrequestor')),
            ],
        ),
    ]
