# Generated by Django 5.0.3 on 2024-04-08 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WastePlastic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wastePlastic_type', models.CharField(max_length=100)),
                ('collection_date', models.DateField(auto_now_add=True)),
                ('wastePlastic_size', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WastePlasticRequestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wastePlastic_type', models.CharField(max_length=100)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('wastePlastic_size', models.PositiveIntegerField()),
                ('wastePlastic_address', models.CharField(max_length=100)),
                ('unique_location', models.CharField(max_length=100)),
                ('latitude', models.FloatField(max_length=50)),
                ('longitude', models.FloatField(max_length=50)),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
