# Generated by Django 5.0.3 on 2024-05-02 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WastePlasticCollectorApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestPickUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_status', models.CharField(choices=[('accept', 'Accept'), ('reject', 'Reject')], default='reject', max_length=100)),
                ('requestId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WastePlasticCollectorApp.wasteplasticrequestor')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
