# Generated by Django 5.0.3 on 2024-05-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WastePlasticCollectorApp', '0002_requestpickup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestpickup',
            name='agent_status',
            field=models.CharField(choices=[('accept', 'Accept'), ('reject', 'Reject'), ('pending', 'Pending')], default='pending', max_length=100),
        ),
    ]
