# Generated by Django 5.0.3 on 2024-04-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WastePlasticCollectorApp', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasteplasticrequestor',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
