# Generated by Django 5.0.3 on 2024-04-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WastePlasticCollectorApp', '0003_wasteplasticrequestor_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wasteplastic',
            name='status',
        ),
        migrations.AddField(
            model_name='wasteplastic',
            name='pickUp_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('on progress', 'On Progress'), ('rejected', 'Rejected')], default='on progress', max_length=100),
        ),
        migrations.AddField(
            model_name='wasteplasticrequestor',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wasteplasticrequestor',
            name='latitude',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wasteplasticrequestor',
            name='longitude',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wasteplasticrequestor',
            name='unique_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wasteplasticrequestor',
            name='wastePlastic_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
