# Generated by Django 5.0.3 on 2024-05-21 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WastePlasticCollectorApp', '0004_alter_wasteplastic_pickup_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LookUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.FloatField(default=1.0)),
                ('CO2_reducedValue', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asign_status', models.CharField(choices=[('asign', 'Asign'), ('take back', 'Take back')], default='asign', max_length=100)),
                ('requestId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WastePlasticCollectorApp.wasteplasticrequestor')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
